

GET http://localhost:3001

### 分隔線 --------------------


POST http://localhost:3001/try-post
Content-Type: application/x-www-form-urlencoded

name=小新&address=台南市

### 分隔線 --------------------

POST http://localhost:3001/try-post
Content-Type: application/json

{"name":"先西", "age": 200}